services:
  web:
    image: php:8.1-apache
    container_name: streamify_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=streamify
      - DB_USER=root
      - DB_PASS=rootpassword
    command: >
      bash -c "
      docker-php-ext-install pdo pdo_mysql &&
      a2enmod rewrite &&
      apache2-foreground
      "

  db:
    image: mysql:8.0
    container_name: streamify_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: streamify
      MYSQL_USER: streamify_user
      MYSQL_PASSWORD: streamify_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: streamify_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data: